stages:
  download_data:
    cmd: python src/download_data.py
    outs:
    - data/raw/reviews.tsv

  data_prep:
    cmd: python src/data_prep.py
    deps:
    - data/raw/reviews.tsv
    - src/data_prep.py
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  train_model:
    cmd: python src/train.py --data data/processed/train.csv --model artifacts/model.pkl
      --vectorizer artifacts/vectorizer.pkl
    deps:
    - data/processed/train.csv
    - src/train.py
    outs:
    - artifacts/model.pkl
    - artifacts/vectorizer.pkl
    metrics:
    - output/train_metrics.json:
        cache: false
        
  evaluate_model:
    cmd: python src/evaluate.py --model artifacts/model.pkl --vectorizer artifacts/vectorizer.pkl
      --test-data data/processed/test.csv
    deps:
    - data/processed/test.csv
    - artifacts/model.pkl
    - artifacts/vectorizer.pkl
    - src/evaluate.py
    metrics:
    - output/metrics.json:
        cache: false
