name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-lint-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: model-training

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage coverage-badge pylint

      - name: Prepare data
        run: |
          python src/data_prep.py \
              --raw-out   data/raw/a1_RestaurantReviews.tsv \
              --train-out data/processed/train.csv \
              --test-out  data/processed/test.csv
      - name: Train model
        run: |
          python src/train.py \
              --data       data/processed/train.csv \
              --vectorizer artifacts/vectorizer.pkl \
              --model      artifacts/model.pkl
      - name: Evaluate model
        run: |
          python src/evaluate.py \
              --model      artifacts/model.pkl \
              --vectorizer artifacts/vectorizer.pkl \
              --test-data  data/processed/test.csv
      - name: Lint with pylint
        run: |
          pylint src/ --fail-under=8.0
        continue-on-error: false

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage html

      - name: Generate coverage badge
        run: |
          coverage-badge -o coverage.svg -f

      - name: Commit coverage badge to repo
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add coverage.svg
          git commit -m 'Update coverage badge [skip ci]' || echo "No changes to commit"
          git push 