name: Data-Prep - Train - Evaluate - Release

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc dvc-gdrive

      - name: Install test/lint dependencies
        run: pip install pytest pylint astroid coverage coverage-badge pyyaml

      - name: Lint with pylint (standard + ML code smells)
        run: |
          pylint --load-plugins=linters.pylint_ml_smells src/ > lint_full.log || true
          SCORE=$(tail -n 2 lint_full.log | grep 'Your code has been rated at' | sed -E 's/.*rated at ([0-9\.]+)\/10.*/\1/')
          echo "Pylint score: $SCORE"
          echo $SCORE > pylint_score.txt
          grep -E "^(.*:[0-9]+:[0-9]+: )?[A-Z][0-9]{4}:" lint_full.log > lint_combined.txt || true

      - name: Upload combined linter output
        uses: actions/upload-artifact@v4
        with:
          name: combined-lint-results
          path: lint_combined.txt

      - name: Generate pylint badge
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          SCORE=$(cat pylint_score.txt)
          COLOR="brightgreen"
          if (( $(echo "$SCORE < 9.0" | bc -l) )); then COLOR="yellow"; fi
          if (( $(echo "$SCORE < 5.0" | bc -l) )); then COLOR="red"; fi
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='150' height='20'>
            <rect width='150' height='20' fill='gray'/>
            <rect x='70' width='80' height='20' fill='$COLOR'/>
            <text x='10' y='14' fill='white' font-family='Verdana' font-size='12'>Pylint</text>
            <text x='75' y='14' fill='white' font-family='Verdana' font-size='12'>$SCORE</text>
          </svg>" > pylint.svg

      - name: Setup DVC
        run: |
          echo '${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}' > service-account.json
          dvc config --local core.analytics false
          dvc config --local core.autostage true
          dvc config --local remote.myremote.url gdrive://1XeB-PlDZXOJWW89yBJ0WEbL4UZwub2I6
          dvc config --local remote.myremote.gdrive_use_service_account true
          dvc config --local remote.myremote.gdrive_service_account_json_file_path service-account.json

      - name: Pull DVC data
        run: |
          mkdir -p artifacts
          dvc pull data/raw/reviews.tsv data/processed/test.csv data/processed/train.csv || true

      - name: Run DVC pipeline
        run: |
          dvc repro

      - name: Push DVC changes
        run: |
          dvc push

      - name: Run tests and calculate ML Test Score
        run: |
          coverage run -m pytest
          coverage report
          python tests/calculate_ml_score.py

      - name: Generate coverage badge
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          coverage-badge -o coverage.svg -f

      - name: Generate ML Test Score badge
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          SCORE=$(cat ml_test_score.txt)
          COLOR="brightgreen"
          if (( $(echo "$SCORE < 5.0" | bc -l) )); then COLOR="yellow"; fi
          if (( $(echo "$SCORE < 3.0" | bc -l) )); then COLOR="red"; fi
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='150' height='20'>
            <rect width='150' height='20' fill='gray'/>
            <rect x='70' width='80' height='20' fill='$COLOR'/>
            <text x='10' y='14' fill='white' font-family='Verdana' font-size='12'>ML Test</text>
            <text x='75' y='14' fill='white' font-family='Verdana' font-size='12'>$SCORE</text>
          </svg>" > ml_test_score.svg

      - name: Commit badges to badge-badges branch
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch origin
          git worktree add ../badge-badges badge-badges || git worktree add ../badge-badges -b badge-badges origin/badge-badges
          rm -f ../badge-badges/coverage.svg ../badge-badges/pylint.svg ../badge-badges/ml_test_score.svg
          cp coverage.svg pylint.svg ml_test_score.svg ../badge-badges/
          cd ../badge-badges
          git add coverage.svg pylint.svg ml_test_score.svg
          git commit -m 'Update badges [skip ci]' || echo "No changes to commit"
          git push origin badge-badges

      - name: Publish artifacts to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view "$VERSION" >/dev/null 2>&1 || \
            gh release create "$VERSION" --title "$VERSION" --notes "Automated build for $VERSION"
          gh release upload "$VERSION" artifacts/model.pkl artifacts/vectorizer.pkl --clobber

      - name: Bump main to next pre-release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          VERSION: ${{ github.ref_name }}   
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Stash any uncommitted changes before switching branches
          git stash push -m "Temporary stash before branch switch"
          git checkout main
          ver="${VERSION#v}"
          IFS='.' read -r MAJ MIN PATCH <<< "$ver"
          NEXT_PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJ}.${MIN}.${NEXT_PATCH}-pre"
          echo "$NEW_VERSION" > version.txt
          git add version.txt
          git commit -m "chore: bump to $NEW_VERSION"
          git push origin main
          PRE_TAG="v${NEW_VERSION}"
          git tag "$PRE_TAG"
          git push origin "$PRE_TAG"