name: Train and Publish Model

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write   
  packages: write  

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: |
          python train.py \
            --data data/a1_RestaurantReviews_HistoricDump.tsv \
            --vec_out models/vectorizer.pkl \
            --model_out models/classifier.joblib

      - name: Archive model artifacts
        run: |
          tar czf models.tar.gz models

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Model artifacts ${{ github.ref_name }}"

      - name: Upload model artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: models.tar.gz
          asset_name: models.tar.gz
          asset_content_type: application/gzip
