name: Train & Release Model

on:
  push:
    tags:
      - '*.*.*'     

permissions:
  contents: write    

jobs:
  train_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .            # installs your model-training package
          pip install lib-ml lib-version  # if you need to fetch your preprocessing & versioning packages

      - name: Make artifacts directory
        run: mkdir -p artifacts

      - name: Train model & emit URL
        run: |
          python - <<EOF
            import os
            from train import train_model  # adjust import path to your entrypoint
            url = train_model(
                data_path="data/reviews.tsv",        # adjust path if needed
                vectorizer_out="artifacts/vectorizer.pkl",
                model_out="artifacts/model.pkl"
            )
            print(f"::set-output name=model_url::{url}")
            EOF
        id: train

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Automated model build for version ${{ github.ref_name }}.
            Download artifacts below.

      - name: Upload Vectorizer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/vectorizer.pkl
          asset_name: vectorizer.pkl
          asset_content_type: application/octet-stream

      - name: Upload Model
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/model.pkl
          asset_name: model.pkl
          asset_content_type: application/octet-stream

      - name: Output model URL
        run: echo "Model URL = ${{ steps.train.outputs.model_url }}"
