name: Train & Release Model

on:
  push:
    tags:
      - '*.*.*'    

permissions:
  contents: write   
jobs:
  train_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python & install deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train, package & publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python train.py \
            --data data/reviews.tsv \
            --vectorizer artifacts/vectorizer.pkl \
            --model artifacts/model.pkl
