name: Train & Release Model

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']      

permissions:
  contents: write                       

jobs:
  train-and-release:
    runs-on: ubuntu-latest

    env:
      DATA_FILE: data/a1_RestaurantReviews_HistoricDump.tsv
      VEC_FILE:  artifacts/vectorizer.pkl
      MODEL_FILE: artifacts/model.pkl
      VERSION:    ${{ github.ref_name }}   

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train.py \
            --data "$DATA_FILE" \
            --vectorizer "$VEC_FILE" \
            --model "$MODEL_FILE"

      - name: Publish artefacts to GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # create release if it doesn't exist
          gh release view "$VERSION" >/dev/null 2>&1 || \
          gh release create "$VERSION" --title "$VERSION" --notes \
            "Automated model build for $VERSION"
          
          # upload (overwrite if already there)
          gh release upload "$VERSION" "$VEC_FILE" "$MODEL_FILE" --clobber
          
          BASE_URL="https://github.com/${{ github.repository }}/releases/download/${VERSION}"
          echo "Vectorizer URL: ${BASE_URL}/$(basename "$VEC_FILE")"
          echo "Model URL:      ${BASE_URL}/$(basename "$MODEL_FILE")"
